// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8hSZKo7T43HUhSNwisf2pW7LMefxfLsk',
    appId: '1:1039216278169:web:95b8a32e7064794b429608',
    messagingSenderId: '1039216278169',
    projectId: 'nootriscan-49e1e',
    authDomain: 'nootriscan-49e1e.firebaseapp.com',
    storageBucket: 'nootriscan-49e1e.firebasestorage.app',
    measurementId: 'G-ZQ4KHVP1S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYFN5EB31125tOEQ9u9tWNfEF3cwPQCk',
    appId: '1:1039216278169:android:259ce05911f6e519429608',
    messagingSenderId: '1039216278169',
    projectId: 'nootriscan-49e1e',
    storageBucket: 'nootriscan-49e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS9Bi5zmeXOGiJ8Htggw7mRT0WG_oRZI0',
    appId: '1:1039216278169:ios:385063e094deab36429608',
    messagingSenderId: '1039216278169',
    projectId: 'nootriscan-49e1e',
    storageBucket: 'nootriscan-49e1e.firebasestorage.app',
    iosClientId: '1039216278169-keghv9uvf8fso7u4lepfbkeuqcrqg0r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nootriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS9Bi5zmeXOGiJ8Htggw7mRT0WG_oRZI0',
    appId: '1:1039216278169:ios:385063e094deab36429608',
    messagingSenderId: '1039216278169',
    projectId: 'nootriscan-49e1e',
    storageBucket: 'nootriscan-49e1e.firebasestorage.app',
    iosClientId: '1039216278169-keghv9uvf8fso7u4lepfbkeuqcrqg0r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nootriscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8hSZKo7T43HUhSNwisf2pW7LMefxfLsk',
    appId: '1:1039216278169:web:626fa886e92c793c429608',
    messagingSenderId: '1039216278169',
    projectId: 'nootriscan-49e1e',
    authDomain: 'nootriscan-49e1e.firebaseapp.com',
    storageBucket: 'nootriscan-49e1e.firebasestorage.app',
    measurementId: 'G-CXWBFZ7SFJ',
  );
}
